### ISSUE TITLE
Level​ ​props​ ​size​ ​chart​

### ISSUE THREAD

**Issue by bymsa17** [bymsa17/EMAX#24]
Imagen comparativa tamaños elementos escenario, puede utilizar thumbnails

- [x] Level​ ​props​ ​size​ ​chart.

**EXPECTED RESULT:**

_Ordenar todos los props que tenemos según el tamaño y meterlo todo a Unity._

**Comment by EvgeniiaD** [comment]
5ee257e5af91dedd5ad2525f7740cf8187179ec8
