### ISSUE TITLE
Create level with temporal textures

### ISSUE THREAD

**Issue by bymsa17** [bymsa17/EMAX#37]
NIVEL​ ​Fase​ ​2:​ ​Modelado​ ​temporal​ ​(puede​ ​utilizar​ ​boxes)

**EXPECTED RESULT:**

_Montar el nivel con todas las texturas (temporales) que tenemos._

**Comment by EvgeniiaD** [comment]
Issue cerrado en el comit; 9cd04e817d031a1d0fb814b51f531e0cf86fbfe5
