### ISSUE TITLE
Create ​final enemy

### ISSUE THREAD

**Issue by bymsa17** [bymsa17/EMAX#40]
ENEMY/NPC​ ​A​ ​Fase​ ​1:​ ​Modelado​ ​final​ ​+​ ​texturizado​ ​temporal​ ​(diffuse)
- [x] Liquido
- [x] Burbuja ácida

**EXPECTED RESULT:**

*Actualizar las texturas  de los "enemigos", que en el nuestro caso sera los líquidos y las burbujas. Añadir sombra.*

**Comment by EvgeniiaD** [comment]
8eae7749b3df0306c9383cfcb6cabbabc68575e3
