### ISSUE TITLE
Create temporal boss

### ISSUE THREAD

**Issue by bymsa17** [bymsa17/EMAX#41]
BOSS/NPC​ ​Fase​ ​1:​ ​Modelado​ ​temporal​ ​(puede​ ​utilizar​ ​boxes)
- [x] Texture boss (Oscuridad)

**EXPECTED RESULT:**

*Crear la textura del BOSS, que en nuestro caso es la Oscuridad que persigue al jugador.*

**Comment by EvgeniiaD** [comment]
816a553ebecea9eceec2dbf5b3b593a44eb799e4
