### ISSUE TITLE
Create basic elements of interface (GUI)

### ISSUE THREAD

**Issue by bymsa17** [bymsa17/EMAX#43]
INTERFAZ​ ​Fase​ ​1:​ ​Elementos​ ​básicos​ ​(provisionales)​ ​de​ ​interfaz​ ​(GUI)

- [x] Diseñar Interfaz.

**EXPECTED RESULT:**

*Diseñar los elementos de la interfaz. Y añadirlo a Unity.*

**Comment by Fokusini** [comment]
Todo creado a falta de pulir si fuese necesario y implementar en unity
